name: Build Release
on: 
  workflow_dispatch:

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      config_package: ${{ steps.config_package.outputs.configPackage }}
    steps:
    - name: Validate Package Config
      id: config_package
      run: |
        if [ "${{ vars.PACKAGE_NAME }}" != "" ]; then
          echo "configPackage=true" >> $GITHUB_OUTPUT;
        else
          echo "configPackage=false" >> $GITHUB_OUTPUT;
        fi

  build:
    needs: config
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      packagePath: Packages/${{ vars.PACKAGE_NAME }}
    if: needs.config.outputs.config_package == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        id: version
        uses: zoexx/github-action-json-file-properties@release
        with: 
            file_path: "${{ env.packagePath }}/package.json"
            prop_path: "version"
    
      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ vars.PACKAGE_NAME }}-${{ steps.version.outputs.value }}.zip" >> $GITHUB_ENV
          echo "unityPackage=${{ vars.PACKAGE_NAME }}-${{ steps.version.outputs.value }}.unitypackage" >> $GITHUB_ENV
          echo "version=${{ steps.version.outputs.value }}" >> $GITHUB_ENV

      - name: Create Package Zip
        working-directory: "${{ env.packagePath }}"
        run: zip -r "${{ github.workspace }}/${{ env.zipFile }}" .
      
      - name: Track Package Meta Files
        run: |
          find "${{ env.packagePath }}/" -name \*.meta | sort | uniq > metaList
          cat metaList

      - name: Cleanup temp directory
        run: |
          rm -rf tempFolder*
          mkdir tempFolder

      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList
          temp-folder: tempFolder
      
      - name: Create Tag
        id: tag_version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ env.version }}"
      
      - name: Make Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            ${{ env.packagePath }}/package.json
          tag_name: ${{ env.version }}
